let token=localStorage.getItem('vigyapan_admin_token')||'';
let DB={};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const api=()=>String(window.VIGYAPAN_CONFIG?.API||'').trim();
let uploadSeq=0;
function showToast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(showToast.t);showToast.t=setTimeout(()=>e.style.display='none',2600)}
function jsonp(url,timeout=8000){return new Promise((resolve,reject)=>{const cb='a_'+Date.now()+'_'+Math.random().toString(16).slice(2);const s=document.createElement('script');const to=setTimeout(()=>{s.remove();delete window[cb];reject(Error('timeout'))},timeout);window[cb]=d=>{clearTimeout(to);s.remove();delete window[cb];resolve(d)};s.onerror=()=>{clearTimeout(to);s.remove();delete window[cb];reject(Error('api error'))};s.src=url+(url.includes('?')?'&':'?')+'callback='+cb;document.body.appendChild(s)})}
async function post(payload){
  if(!api()) throw Error('Apps Script URL missing');
  const r=await fetch(api(),{method:'POST',mode:'no-cors',cache:'no-store',body:JSON.stringify({...payload,token})});
  return {ok:true,opaque:r.type==='opaque'};
}
async function getVersion(){try{const d=await jsonp(api()+'?action=version',6000);return String(d.version||'')}catch(e){return ''}}
async function waitForVersion(before,timeout=9000){const until=Date.now()+timeout;while(Date.now()<until){const v=await getVersion();if(v&&v!==String(before))return v;await new Promise(r=>setTimeout(r,350))}return ''}
async function login(){const btn=document.querySelector('.loginBox button');try{if(btn){btn.disabled=true;btn.textContent='Signing in…'}const p=$('#password').value;if(!p)return showToast('Enter password');const d=await jsonp(api()+'?action=login&password='+encodeURIComponent(p),7000);if(!d.ok)return showToast(d.error||'Invalid password');token=d.token;localStorage.setItem('vigyapan_admin_token',token);showApp();load().catch(()=>showToast('Data load failed — retrying…'));}catch(e){showToast('Login failed. Check config.js / Apps Script.')}finally{if(btn){btn.disabled=false;btn.textContent='Login'}}}
function logout(){localStorage.removeItem('vigyapan_admin_token');token='';location.reload()}
function showApp(){if($('#login'))$('#login').classList.add('hidden');if($('#app'))$('#app').classList.remove('hidden')}
async function start(){if(!token)return;try{const d=await jsonp(api()+'?action=authCheck&token='+encodeURIComponent(token),5000);if(!d.ok){localStorage.removeItem('vigyapan_admin_token');token='';return}showApp();bindTabs();renderDashboard();load().catch(()=>showToast('Could not load CMS data'));}catch(e){localStorage.removeItem('vigyapan_admin_token');token='';showToast('Session expired. Please login again.')}}
async function load(){const d=await jsonp(api()+'?action=public',10000);if(d&&d.settings){DB=d;return d}throw Error('Invalid CMS data')}
async function refresh(msg='Saved'){const before=DB.version||await getVersion();const v=await waitForVersion(before,9000);try{await load()}catch(e){}if(v)DB.version=v;showToast(msg);return true}
function bindTabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.tab);if(innerWidth<800)toggleSide()})}
function toggleSide(){document.querySelector('aside')?.classList.toggle('open')}
function renderDashboard(){renderTab('dashboard')}
function renderTab(tab){const c=$('#content');if(!c)return;if(tab==='dashboard')c.innerHTML=dashboard();else if(tab==='settings')c.innerHTML=settings();else if(tab==='hero')c.innerHTML=crud('HERO','Hero Slider','hero');else if(tab==='services')c.innerHTML=crud('SERVICES','Services','services');else if(tab==='products')c.innerHTML=crud('PRODUCTS','Products','products');else if(tab==='plans')c.innerHTML=crud('PLANS','Plans','plans');else if(tab==='gallery')c.innerHTML=galleryAdmin()}
function dashboard(){return `<div class="pageHead"><div><h1>Dashboard</h1><p>Google Sheet + Drive connected CMS.</p></div><a class="btn gold" href="index.html" target="_blank">Open Public Website ↗</a></div><div class="stats"><div class="stat"><b>${DB.hero?.length||0}</b><span>Hero Slides</span></div><div class="stat"><b>${DB.services?.length||0}</b><span>Services</span></div><div class="stat"><b>${DB.products?.length||0}</b><span>Products</span></div><div class="stat"><b>${gallerySections().length}</b><span>Gallery Folders</span></div></div><div class="panel livePanel"><h3>Live Update</h3><p>After Save, the public website detects the new version automatically. No manual refresh required.</p></div>`}
const settingKeys=['siteName','siteTagline','logoText','logoSub','primaryColor','phone','email','address','whatsapp','facebook','instagram','youtube','linkedin','heroInterval','aboutEyebrow','aboutTitle','aboutText','galleryTitle','gallerySubtitle','productsTitle','servicesTitle','plansTitle','contactTitle','contactSubtitle','footerText'];
function settings(){return `<div class="pageHead"><div><h1>Site Settings</h1><p>Change global website content and logo.</p></div></div><div class="panel"><div class="logoUpload"><div><b>Website Logo</b><small>Upload PNG/JPG/WebP. Small files upload directly.</small></div><div class="logoPreview">${setting('logoUrl')?`<img src="${esc(setting('logoUrl'))}">`:'No logo'}</div><input id="logoFile" type="file" accept="image/*" onchange="uploadLogo(event)"><div id="logoStatus" class="miniStatus"></div></div><div class="formGrid">${settingKeys.map(k=>`<div class="field"><label>${esc(k)}</label><input id="set_${esc(k)}" value="${esc(setting(k))}"></div>`).join('')}</div><div class="saveBar"><button class="btn green" onclick="saveSettings()">Save Changes</button></div></div><div class="panel"><h3>Admin Password</h3><div class="row"><input id="newPass" type="password" placeholder="Minimum 6 characters" style="flex:1;padding:9px;border:1px solid #dbe4ea;border-radius:7px"><button class="btn" onclick="changePassword()">Change Password</button></div></div>`}
function setting(k){const x=(DB.settings||[]).find(r=>r.key===k);return x?x.value:''}
async function uploadLogo(e){const f=e.target.files?.[0];if(!f)return;const s=$('#logoStatus');s.textContent='Preparing logo…';try{const name='LOGO_'+Date.now()+'_'+safeFileName(f.name);const url=await uploadAndGetUrl(f,name,m=>s.textContent=m);await post({action:'saveSettings',items:[{key:'logoUrl',value:url}]});await refresh('Logo uploaded & published');renderTab('settings')}catch(err){s.textContent='Failed: '+err.message}}
async function saveSettings(){try{const items=settingKeys.map(k=>({key:k,value:$('#set_'+k)?.value||''}));await post({action:'saveSettings',items});await refresh('Settings saved — website updated');renderTab('settings')}catch(e){showToast(e.message)}}
async function changePassword(){try{const p=$('#newPass').value;if(!p||p.length<6)return showToast('Minimum 6 characters');await post({action:'changePassword',newPassword:p});$('#newPass').value='';showToast('Password changed')}catch(e){showToast(e.message)}}
const schemas={
 hero:{sheet:'HERO',fields:[['imageUrl','Image URL / uploaded file','text'],['titleSmall','Small Heading','text'],['title1','Main Heading 1','text'],['title2','Main Heading 2','text'],['description','Description','textarea'],['button1','Button 1','text'],['button1Link','Button 1 Link','text'],['button2','Button 2','text'],['button2Link','Button 2 Link','text'],['sort','Order','number'],['active','Active','selectYESNO']]},
 services:{sheet:'SERVICES',fields:[['icon','Icon / Emoji','text'],['name','Service Name','text'],['description','Description','text'],['sort','Order','number'],['active','Active','selectYESNO']]},
 products:{sheet:'PRODUCTS',fields:[['name','Product Name','text'],['price','Price','text'],['imageUrl','Image URL / uploaded file','text'],['shortDescription','Short Description','text'],['description','Full Description','textarea'],['features','Features (use | between items)','textarea'],['category','Category','text'],['sort','Order','number'],['active','Active','selectYESNO']]},
 plans:{sheet:'PLANS',fields:[['name','Plan Name','text'],['tagline','Tagline','text'],['price','Price','text'],['period','Period','text'],['color','Color','text'],['features','Features (use | between items)','textarea'],['sort','Order','number'],['active','Active','selectYESNO'],['buttonText','Button Text','text'],['buttonLink','Button Link','text']]},
 gallery:{sheet:'GALLERY',fields:[['section','Folder / Section','text'],['type','Type','selectMedia'],['title','Title','text'],['mediaUrl','Media URL / uploaded file','text'],['thumbUrl','Thumbnail URL','text'],['sort','Order','number'],['active','Active','selectYESNO']]}
};
function crud(type,title,key){const rows=(DB[key]||[]).slice().sort((a,b)=>(+a.sort||0)-(+b.sort||0));return `<div class="pageHead"><div><h1>${title}</h1><p>Add, edit, delete and reorder content.</p></div><div><button class="btn gold" onclick="editItem('${key}','')">+ Add New</button>${key==='hero'||key==='gallery'?` <button class="btn" onclick="bulkUpload('${key}')">⇧ Bulk Upload</button>`:''}</div></div><div class="panel"><div class="list">${rows.length?rows.map(x=>itemRow(key,x)).join(''):'<div class="empty">No items yet.</div>'}</div></div>`}
function itemRow(key,x){const image=x.imageUrl||x.mediaUrl||'';return `<div class="item"><div>${image&&String(x.type)!=='video'?`<img class="thumb" src="${esc(image)}" loading="lazy">`:String(x.type)==='video'?'<div class="thumb videoThumb">▶ VIDEO</div>':'<div class="thumb"></div>'}</div><div><h4>${esc(x.name||x.title||x.section||'Untitled')}</h4><p>${esc(x.price||x.description||x.shortDescription||x.section||'')}</p></div><div class="itemActions"><button class="iconBtn" onclick='editItem("${key}","${esc(x.id)}")'>Edit</button><button class="iconBtn danger" onclick='removeItem("${key}","${esc(x.id)}")'>Delete</button></div></div>`}
function gallerySections(){const map={};(DB.gallery||[]).filter(x=>String(x.active).toUpperCase()==='YES').forEach(x=>{const s=String(x.section||'New Gallery').trim()||'New Gallery';(map[s]??=[]).push(x)});return Object.entries(map).sort((a,b)=>String(a[0]).localeCompare(String(b[0])))}
function galleryAdmin(){return `<div class="pageHead"><div><h1>Gallery / Video</h1><p>Folders contain multiple photos/videos. Customers open a folder to browse, slide and zoom.</p></div><div><button class="btn gold" onclick="editItem('gallery','')">+ New Folder / Media</button> <button class="btn" onclick="bulkUpload('gallery')">⇧ Bulk Upload</button></div></div><div class="folderAdminGrid">${gallerySections().map(([name,rows])=>folderAdminCard(name,rows)).join('')||'<div class="empty">No gallery folders yet.</div>'}</div>`}
function folderAdminCard(name,rows){const cover=rows.find(x=>x.type!=='video')?.mediaUrl||rows[0]?.thumbUrl||'';return `<div class="folderCard"><div class="folderCover">${cover?`<img src="${esc(cover)}" loading="lazy">`:'<span>MEDIA</span>'}</div><div class="folderInfo"><h3>▱ ${esc(name)}</h3><span>${rows.length} item${rows.length!==1?'s':''}</span><button class="btn mini" onclick="toggleFolder(this)">Open Folder</button></div><div class="folderItems">${rows.map(x=>itemRow('gallery',x)).join('')}</div></div>`}
function toggleFolder(btn){const card=btn.closest('.folderCard');card.classList.toggle('open');btn.textContent=card.classList.contains('open')?'Close Folder':'Open Folder'}
function editItem(key,id){const s=schemas[key],row=(DB[key]||[]).find(x=>String(x.id)===String(id))||{id:key.toUpperCase().slice(0,2)+(Date.now()%100000),sort:(DB[key]||[]).length+1,active:'YES'};$('#modal').innerHTML=`<div class="modalBox"><div class="modalHead"><h2>${id?'Edit':'Add'} ${key}</h2><button class="close" onclick="closeModal()">×</button></div><input type="hidden" id="f_id" value="${esc(row.id)}"><div class="formGrid" id="editForm" style="margin-top:15px">${s.fields.map(([f,l,t])=>field(f,l,t,row[f]??'')).join('')}</div>${['hero','products','gallery'].includes(key)?uploadUI(key):''}<div class="saveBar"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn green" onclick="saveItem('${key}')">Save & Update Website</button></div></div>`;$('#modal').classList.add('show')}
function field(f,l,t,v){if(t==='textarea')return `<div class="field full"><label>${l}</label><textarea id="f_${f}">${esc(v)}</textarea></div>`;if(t==='selectYESNO')return `<div class="field"><label>${l}</label><select id="f_${f}"><option ${String(v).toUpperCase()==='YES'?'selected':''}>YES</option><option ${String(v).toUpperCase()!=='YES'?'selected':''}>NO</option></select></div>`;if(t==='selectMedia')return `<div class="field"><label>${l}</label><select id="f_${f}"><option ${v==='image'?'selected':''}>image</option><option ${v==='video'?'selected':''}>video</option></select></div>`;return `<div class="field"><label>${l}</label><input id="f_${f}" type="${t==='number'?'number':'text'}" value="${esc(v)}"></div>`}
function uploadUI(key){return `<div class="uploadBox" style="margin-top:15px"><b>Upload ${key==='gallery'?'multiple images/videos':'image'}</b><br><small>Image ≤150 KB and video ≤500 KB upload directly; larger files are compressed in browser.</small><input id="fileInput" type="file" ${key==='gallery'?'multiple':''} accept="${key==='gallery'?'image/*,video/*':'image/*'}" onchange="previewFiles(event,'${key}')"><div class="previewGrid" id="previewGrid"></div><div class="uploadQueue" id="uploadQueue"></div></div>`}
function previewFiles(e,key){const box=$('#previewGrid');box.innerHTML='';[...e.target.files].forEach(f=>{const u=URL.createObjectURL(f);box.insertAdjacentHTML('beforeend',f.type.startsWith('video/')?`<video src="${u}" controls></video>`:`<img src="${u}">`)})}
async function saveItem(key){try{const s=schemas[key],obj={id:$('#f_id').value};s.fields.forEach(([f])=>obj[f]=$('#f_'+f)?.value||'');const files=$('#fileInput')?.files;if(files&&files.length){if(key==='gallery'&&files.length>1){return doBulkUpload(key,files,true,obj)}const f=files[0];ensureQueue();setUploadStatus(f.name,'Preparing…','work');const name='UP_'+Date.now()+'_'+safeFileName(f.name);const url=await uploadAndGetUrl(f,name,m=>setUploadStatus(f.name,m,'work'));if(key==='gallery'){obj.mediaUrl=url;obj.thumbUrl=url;obj.type=f.type.startsWith('video/')?'video':'image'}else obj.imageUrl=url}const before=DB.version||await getVersion();await post({action:'saveRows',sheet:s.sheet,rows:[obj]});await waitForVersion(before);await load();closeModal();renderTab(key);showToast('Saved ✓ Website updated');}catch(e){showToast('Save failed: '+e.message)}}
function safeFileName(n){return String(n||'file').replace(/[^a-zA-Z0-9._-]/g,'_')}
function ensureQueue(){if($('#uploadQueue'))return;const box=$('#previewGrid');box.insertAdjacentHTML('afterend','<div class="uploadQueue" id="uploadQueue"></div>')}
function setUploadStatus(name,msg,state='work'){ensureQueue();const id='uq_'+(++uploadSeq);let el=document.createElement('div');el.className='uploadRow '+state;el.id=id;el.innerHTML=`<span class="uploadName">${esc(name)}</span><span class="uploadState">${esc(msg)}</span>`;$('#uploadQueue').appendChild(el);return id}
function updateUploadStatus(id,msg,state='work'){const el=document.getElementById(id);if(!el)return;el.className='uploadRow '+state;const s=el.querySelector('.uploadState');if(s)s.textContent=msg}
async function uploadAndGetUrl(file,name,onStatus){const data=await prepareFile(file,onStatus);onStatus?.('Uploading to Drive…');await post({action:'uploadMedia',fileName:name,mimeType:(data.match(/^data:([^;]+);/)||[])[1]||file.type,data});onStatus?.('Verifying…');for(let i=0;i<14;i++){try{const d=await jsonp(api()+'?action=mediaByName&name='+encodeURIComponent(name),5000);if(d.ok){onStatus?.('Uploaded ✓','done');return d.url}}catch(e){}await new Promise(r=>setTimeout(r,250))}onStatus?.('Upload verification timed out','error');throw Error('Drive upload could not be verified')}
async function bulkUpload(key){const accept=key==='hero'?'image/*':'image/*,video/*';$('#modal').innerHTML=`<div class="modalBox"><div class="modalHead"><h2>Bulk Upload ${key==='gallery'?'Gallery':'Hero'}</h2><button class="close" onclick="closeModal()">×</button></div>${key==='gallery'?`<div class="field"><label>Folder / Section name</label><input id="bulkSection" value="New Gallery" placeholder="e.g. Business Cards"></div>`:''}<p class="uploadHint">Select multiple files. Upload runs 4 at a time for speed.</p><div class="uploadBox"><input id="bulkFiles" type="file" multiple accept="${accept}"><div class="previewGrid" id="previewGrid"></div><div class="uploadQueue" id="uploadQueue"></div></div><div class="saveBar"><button class="btn" onclick="closeModal()">Close</button><button class="btn green" onclick="doBulkUpload('${key}')">Upload & Publish</button></div></div>`;$('#modal').classList.add('show');$('#bulkFiles').onchange=e=>previewFiles(e,key)}
async function doBulkUpload(key,passedFiles,fromEdit=false,baseObj=null){const input=$('#bulkFiles')||$('#fileInput');const files=passedFiles?[...passedFiles]:[...(input?.files||[])];if(!files.length)return showToast('Select files first');const section=key==='gallery'?String($('#bulkSection')?.value||baseObj?.section||'New Gallery').trim():' ';const sheet=schemas[key].sheet;let order=(DB[key]||[]).length+1,cursor=0;const results=new Array(files.length);const concurrency=4;async function worker(){while(true){const i=cursor++;if(i>=files.length)return;const f=files[i];const id=setUploadStatus(f.name,'Preparing…','work');try{const name='BULK_'+Date.now()+'_'+i+'_'+safeFileName(f.name);const url=await uploadAndGetUrl(f,name,m=>updateUploadStatus(id,m,m==='Uploaded ✓'?'done':'work'));results[i]={f,url,id}}catch(e){results[i]={f,error:e.message,id};updateUploadStatus(id,'Failed: '+e.message,'error')}}}await Promise.all(Array.from({length:Math.min(concurrency,files.length)},worker));const rows=[];results.forEach((r,i)=>{if(!r||r.error)return;const f=r.f,base=f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ');const obj={id:key.toUpperCase().slice(0,2)+(Date.now()%100000)+i+Math.floor(Math.random()*99),sort:order++,active:'YES'};if(key==='hero')Object.assign(obj,{imageUrl:r.url,titleSmall:'LET’S GROW YOUR BRAND TOGETHER',title1:base,title2:'Powerful Results',description:'Creative advertising solutions for your business.',button1:'Explore Services',button1Link:'#services',button2:'Get a Free Quote',button2Link:'#contact'});else Object.assign(obj,{section:section||'New Gallery',type:f.type.startsWith('video/')?'video':'image',title:base,mediaUrl:r.url,thumbUrl:r.url});rows.push(obj)});if(fromEdit&&baseObj&&rows[0]){Object.assign(baseObj,rows[0]);const before=DB.version||await getVersion();await post({action:'saveRows',sheet,rows:[baseObj]});await waitForVersion(before)}else if(rows.length){const before=DB.version||await getVersion();await post({action:'saveRows',sheet,rows});await waitForVersion(before)}await load();renderTab(key);showToast(`${rows.length} file${rows.length!==1?'s':''} uploaded ✓`);if(!results.some(r=>r?.error))setTimeout(closeModal,500)}
async function prepareFile(file,onStatus){if(file.type.startsWith('image/')){if(file.size<=150*1024){onStatus?.('Small image — direct upload ✓');return toData(file)}onStatus?.('Compressing image…');return compressImage(file)}if(file.type.startsWith('video/')){if(file.size<=500*1024){onStatus?.('Small video — direct upload ✓');return toData(file)}onStatus?.('Compressing video…');return compressVideo(file)}return toData(file)}
function toData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('File read failed'));r.readAsDataURL(file)})}
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{let scale=Math.min(1,1600/Math.max(img.width,img.height)),q=.82,data='';for(let pass=0;pass<6;pass++){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));const x=c.getContext('2d',{alpha:false});x.drawImage(img,0,0,c.width,c.height);data=c.toDataURL('image/jpeg',q);if(data.length*0.75<=150*1024)break;q=Math.max(.38,q-.09);scale*=.84}resolve(data)};img.onerror=()=>reject(Error('Image decode failed'));img.src=r.result};r.onerror=()=>reject(Error('File read failed'));r.readAsDataURL(file)})}
function compressVideo(file){return new Promise(async resolve=>{try{if(!('MediaRecorder'in window)){resolve(await toData(file));return}const v=document.createElement('video');v.src=URL.createObjectURL(file);v.muted=true;v.playsInline=true;await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=rej});const duration=Math.max(1,v.duration||1),maxDim=640,scale=Math.min(1,maxDim/Math.max(v.videoWidth,v.videoHeight));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(v.videoWidth*scale));c.height=Math.max(1,Math.round(v.videoHeight*scale));const ctx=c.getContext('2d');const stream=c.captureStream(12);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp8')?'video/webm;codecs=vp8':'video/webm';const targetBits=Math.max(60000,Math.min(220000,450*1024*8/duration));const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:targetBits});const chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:mime});const rr=new FileReader();rr.onload=()=>resolve(rr.result);rr.readAsDataURL(blob)};rec.start(400);const draw=()=>{if(v.ended){rec.stop();return}ctx.drawImage(v,0,0,c.width,c.height);requestAnimationFrame(draw)};await v.play();draw()}catch(e){resolve(await toData(file))}})}
async function removeItem(key,id){if(!confirm('Delete this item?'))return;try{const before=DB.version||await getVersion();await post({action:'deleteRow',sheet:schemas[key].sheet,id});await waitForVersion(before);await load();renderTab(key);showToast('Deleted ✓')}catch(e){showToast('Delete failed: '+e.message)}}
function closeModal(){$('#modal').classList.remove('show');$('#modal').innerHTML=''}
if(token)start();
