let token=localStorage.getItem('vigyapan_admin_token')||'';let DB={};const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const api=()=>window.VIGYAPAN_CONFIG.API;
function showToast(t){const e=$('#toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2600)}
function jsonp(url){return new Promise((resolve,reject)=>{const cb='a_'+Date.now()+Math.random().toString(16).slice(2);const s=document.createElement('script');const to=setTimeout(()=>{s.remove();delete window[cb];reject(Error('timeout'))},12000);window[cb]=d=>{clearTimeout(to);s.remove();delete window[cb];resolve(d)};s.onerror=()=>{clearTimeout(to);s.remove();delete window[cb];reject(Error('api error'))};s.src=url+'&callback='+cb;document.body.appendChild(s)})}
async function login(){try{const p=$('#password').value;const d=await jsonp(api()+'?action=login&password='+encodeURIComponent(p));if(!d.ok)return showToast(d.error);token=d.token;localStorage.setItem('vigyapan_admin_token',token);start()}catch(e){showToast('Check Apps Script URL in config.js')}}
function logout(){localStorage.removeItem('vigyapan_admin_token');token='';location.reload()}
async function start(){if(!token)return;try{const d=await jsonp(api()+'?action=authCheck&token='+encodeURIComponent(token));if(!d.ok){localStorage.removeItem('vigyapan_admin_token');token='';return}$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load();bindTabs();renderDashboard()}catch(e){localStorage.removeItem('vigyapan_admin_token');token='';showToast('Session expired. Please login again.')}}
async function load(){const d=await jsonp(api()+'?action=public');DB=d}
function bindTabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.tab);if(innerWidth<800)toggleSide()})}
function toggleSide(){document.querySelector('aside').classList.toggle('open')}
function renderDashboard(){renderTab('dashboard')}
function renderTab(tab){const c=$('#content');if(tab==='dashboard')c.innerHTML=dashboard();else if(tab==='settings')c.innerHTML=settings();else if(tab==='hero')c.innerHTML=crud('HERO','Hero Slider','hero');else if(tab==='services')c.innerHTML=crud('SERVICES','Services','services');else if(tab==='products')c.innerHTML=crud('PRODUCTS','Products','products');else if(tab==='plans')c.innerHTML=crud('PLANS','Plans','plans');else if(tab==='gallery')c.innerHTML=crud('GALLERY','Gallery / Video','gallery')}
function dashboard(){return `<div class="pageHead"><div><h1>Dashboard</h1><p>Everything is connected to your Google Sheet + Drive.</p></div><a class="btn gold" href="index.html" target="_blank">Open Public Website ↗</a></div><div class="stats"><div class="stat"><b>${DB.hero?.length||0}</b><span>Hero Slides</span></div><div class="stat"><b>${DB.services?.length||0}</b><span>Services</span></div><div class="stat"><b>${DB.products?.length||0}</b><span>Products</span></div><div class="stat"><b>${DB.gallery?.length||0}</b><span>Gallery / Videos</span></div></div><div class="panel" style="margin-top:15px"><h3>Live Update</h3><p style="font-size:12px;color:#607582;line-height:1.7">Save any change here and the public website automatically picks it up within a few seconds. No manual website refresh is required. The public page polls the CMS in the background.</p></div>`}
function settings(){const keys=['siteName','siteTagline','logoText','logoSub','primaryColor','phone','email','address','whatsapp','facebook','instagram','youtube','linkedin','heroInterval','aboutEyebrow','aboutTitle','aboutText','galleryTitle','gallerySubtitle','productsTitle','servicesTitle','plansTitle','contactTitle','contactSubtitle','footerText'];return `<div class="pageHead"><div><h1>Site Settings</h1><p>Change global website content.</p></div></div><div class="panel"><div class="formGrid">${keys.map(k=>`<div class="field"><label>${k}</label><input id="set_${k}" value="${esc(setting(k))}"></div>`).join('')}</div><div class="saveBar"><button class="btn green" onclick="saveSettings()">Save Changes</button></div></div><div class="panel"><h3>Admin Password</h3><div class="row"><input id="newPass" type="password" placeholder="Minimum 6 characters" style="flex:1;padding:9px;border:1px solid #dbe4ea;border-radius:7px"><button class="btn" onclick="changePassword()">Change Password</button></div></div>`}
function setting(k){const x=(DB.settings||[]).find(r=>r.key===k);return x?x.value:''}
async function saveSettings(){const keys=[...document.querySelectorAll('[id^="set_"]')].map(x=>x.id.slice(4));const items=keys.map(k=>({key:k,value:$('#set_'+k).value}));await post({action:'saveSettings',items});await refresh('Settings saved')}
async function changePassword(){await post({action:'changePassword',newPassword:$('#newPass').value});$('#newPass').value='';showToast('Password changed')}
const schemas={
hero:{sheet:'HERO',fields:[['imageUrl','Image URL / uploaded file','text'],['titleSmall','Small Heading','text'],['title1','Main Heading 1','text'],['title2','Main Heading 2','text'],['description','Description','textarea'],['button1','Button 1','text'],['button1Link','Button 1 Link','text'],['button2','Button 2','text'],['button2Link','Button 2 Link','text'],['sort','Order','number'],['active','Active','selectYESNO']]},
services:{sheet:'SERVICES',fields:[['icon','Icon / Emoji','text'],['name','Service Name','text'],['description','Description','text'],['sort','Order','number'],['active','Active','selectYESNO']]},
products:{sheet:'PRODUCTS',fields:[['name','Product Name','text'],['price','Price','text'],['imageUrl','Image URL / uploaded file','text'],['shortDescription','Short Description','text'],['description','Full Description','textarea'],['features','Features (use | between items)','textarea'],['category','Category','text'],['sort','Order','number'],['active','Active','selectYESNO']]},
plans:{sheet:'PLANS',fields:[['name','Plan Name','text'],['tagline','Tagline','text'],['price','Price','text'],['period','Period','text'],['color','Color','text'],['features','Features (use | between items)','textarea'],['sort','Order','number'],['active','Active','selectYESNO'],['buttonText','Button Text','text'],['buttonLink','Button Link','text']]},
gallery:{sheet:'GALLERY',fields:[['section','Section','text'],['type','Type','selectMedia'],['title','Title','text'],['mediaUrl','Media URL / uploaded file','text'],['thumbUrl','Thumbnail URL','text'],['sort','Order','number'],['active','Active','selectYESNO']]}
};
function crud(type,title,key){const rows=(DB[key]||[]).sort((a,b)=>(+a.sort||0)-(+b.sort||0));return `<div class="pageHead"><div><h1>${title}</h1><p>Add, edit, delete and reorder content.</p></div><button class="btn gold" onclick="editItem('${key}','')">+ Add New</button>${key==='hero'||key==='gallery'?`<button class="btn" style="margin-left:7px" onclick="bulkUpload('${key}')">⇧ Bulk Upload</button>`:''}</div><div class="panel"><div class="list">${rows.length?rows.map(x=>itemRow(key,x)).join(''):'<div class="empty">No items yet. Click Add New.</div>'}</div></div>`}
function itemRow(key,x){let image=x.imageUrl||x.mediaUrl||'';return `<div class="item"><div>${image&&String(x.type)!=='video'?`<img class="thumb" src="${esc(image)}">`:String(x.type)==='video'?'<div class="thumb" style="display:grid;place-items:center">▶ VIDEO</div>':'<div class="thumb"></div>'}</div><div><h4>${esc(x.name||x.title||x.section||'Untitled')}</h4><p>${esc(x.price||x.description||x.shortDescription||x.section||'')}</p></div><div class="itemActions"><button class="iconBtn" onclick='editItem("${key}","${esc(x.id)}")'>Edit</button><button class="iconBtn danger" onclick='removeItem("${key}","${esc(x.id)}")'>Delete</button></div></div>`}
function editItem(key,id){const s=schemas[key], row=(DB[key]||[]).find(x=>String(x.id)===String(id))||{id:key.toUpperCase().slice(0,2)+(Date.now()%100000)};$('#modal').innerHTML=`<div class="modalBox"><div class="modalHead"><h2>${id?'Edit':'Add'} ${key}</h2><button class="close" onclick="closeModal()">×</button></div><input type="hidden" id="f_id" value="${esc(row.id)}"><div class="formGrid" id="editForm" style="margin-top:15px">${s.fields.map(([f,l,t])=>field(f,l,t,row[f]??'')).join('')}</div>${['hero','products','gallery'].includes(key)?uploadUI(key):''}<div class="saveBar"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn green" onclick="saveItem('${key}')">Save & Update Website</button></div></div>`;$('#modal').classList.add('show')}
function field(f,l,t,v){if(t==='textarea')return `<div class="field full"><label>${l}</label><textarea id="f_${f}">${esc(v)}</textarea></div>`;if(t==='selectYESNO')return `<div class="field"><label>${l}</label><select id="f_${f}"><option ${String(v).toUpperCase()==='YES'?'selected':''}>YES</option><option ${String(v).toUpperCase()!=='YES'?'selected':''}>NO</option></select></div>`;if(t==='selectMedia')return `<div class="field"><label>${l}</label><select id="f_${f}"><option ${v==='image'?'selected':''}>image</option><option ${v==='video'?'selected':''}>video</option></select></div>`;return `<div class="field"><label>${l}</label><input id="f_${f}" type="${t==='number'?'number':'text'}" value="${esc(v)}"></div>`}
function uploadUI(key){return `<div class="uploadBox" style="margin-top:15px"><b>Upload ${key==='gallery'?'multiple images/videos':'image'}</b><br><small>Files are compressed in your browser before upload.</small><input id="fileInput" type="file" ${key==='gallery'?'multiple':''} accept="${key==='gallery'?'image/*,video/*':'image/*'}" onchange="previewFiles(event,'${key}')"><div class="previewGrid" id="previewGrid"></div></div>`}
function previewFiles(e,key){const box=$('#previewGrid');box.innerHTML='';[...e.target.files].forEach(f=>{const u=URL.createObjectURL(f);box.insertAdjacentHTML('beforeend',f.type.startsWith('video/')?`<video src="${u}" controls></video>`:`<img src="${u}">`)})}
async function saveItem(key){const s=schemas[key], obj={id:$('#f_id').value};s.fields.forEach(([f])=>obj[f]=$('#f_'+f)?.value||'');const files=$('#fileInput')?.files;if(files&&files.length){if(key==='gallery'&&files.length>1){closeModal();return doBulkUpload(key)}for(const f of files){const name='UP_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)+'_'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const url=await uploadAndGetUrl(f,name);if(key==='gallery'){obj.mediaUrl=url;obj.thumbUrl=url}else{obj.imageUrl=url}}}await post({action:'saveRows',sheet:s.sheet,rows:[obj]});await refresh('Saved — website updated automatically');closeModal();renderTab(key)}
async function uploadAndGetUrl(file,name){const data=await compressFile(file);await post({action:'uploadMedia',fileName:name,data});for(let i=0;i<8;i++){await new Promise(r=>setTimeout(r,700));try{const d=await jsonp(api()+'?action=mediaByName&name='+encodeURIComponent(name));if(d.ok)return d.url}catch(e){}}throw Error('Upload verification failed')}
async function bulkUpload(key){const accept=key==='hero'?'image/*':'image/*,video/*';$('#modal').innerHTML=`<div class="modalBox"><div class="modalHead"><h2>Bulk Upload ${key}</h2><button class="close" onclick="closeModal()">×</button></div><p style="font-size:11px;color:#71838f">Select multiple files. Each file becomes a separate item with a ready-to-edit title. Files are compressed before upload.</p><div class="uploadBox"><input id="bulkFiles" type="file" multiple accept="${accept}"><div class="previewGrid" id="previewGrid"></div></div><div class="saveBar"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn green" onclick="doBulkUpload('${key}')">Upload & Publish</button></div></div>`;$('#modal').classList.add('show');$('#bulkFiles').onchange=e=>previewFiles(e,key)}
async function doBulkUpload(key){const files=[...$('#bulkFiles').files];if(!files.length)return showToast('Select files first');const sheet=schemas[key].sheet;let order=(DB[key]||[]).length+1;for(const f of files){const name='BULK_'+Date.now()+'_'+Math.random().toString(36).slice(2,7)+'_'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');showToast('Uploading '+f.name);const url=await uploadAndGetUrl(f,name);const base=f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ');let obj={id:key.toUpperCase().slice(0,2)+(Date.now()%100000)+Math.floor(Math.random()*99),sort:order++,active:'YES'};if(key==='hero')Object.assign(obj,{imageUrl:url,titleSmall:'LET’S GROW YOUR BRAND TOGETHER',title1:base,title2:'Powerful Results',description:'Creative advertising solutions for your business.',button1:'Explore Services',button1Link:'#services',button2:'Get a Free Quote',button2Link:'#contact'});else Object.assign(obj,{section:f.type.startsWith('video/')?'Video Production':'New Gallery',type:f.type.startsWith('video/')?'video':'image',title:base,mediaUrl:url,thumbUrl:url});await post({action:'saveRows',sheet,rows:[obj]})}await refresh('Bulk upload complete — website updated');closeModal();renderTab(key)}
async function removeItem(key,id){if(!confirm('Delete this item?'))return;await post({action:'deleteRow',sheet:schemas[key].sheet,id});await refresh('Deleted — website updated automatically');renderTab(key)}
async function post(body){body.token=token;await fetch(api(),{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)});return {ok:true}}
async function refresh(msg){await new Promise(r=>setTimeout(r,900));try{DB=await jsonp(api()+'?action=public');showToast(msg)}catch(e){showToast('Saved. Reloading CMS data failed; public site will still sync.')}}
async function compressFile(file){if(file.type.startsWith('image/'))return await compressImage(file);if(file.type.startsWith('video/'))return await compressVideo(file);return await toData(file)}
function toData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image();const r=new FileReader();r.onload=()=>{img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);const x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);let q=.82,data=c.toDataURL('image/jpeg',q);while(data.length>850000&&q>.35){q-=.07;data=c.toDataURL('image/jpeg',q)}resolve(data)};img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function compressVideo(file){return new Promise(async resolve=>{if(!('MediaRecorder' in window))return resolve(await toData(file));const v=document.createElement('video');v.src=URL.createObjectURL(file);v.muted=true;v.playsInline=true;await new Promise(r=>v.onloadedmetadata=r);const c=document.createElement('canvas');const scale=Math.min(1,640/Math.max(v.videoWidth,v.videoHeight));c.width=Math.round(v.videoWidth*scale);c.height=Math.round(v.videoHeight*scale);const ctx=c.getContext('2d');const stream=c.captureStream(15);let mime='video/webm;codecs=vp8';if(!MediaRecorder.isTypeSupported(mime))mime='video/webm';const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:250000});const chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:mime});const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(blob)};rec.start();const draw=()=>{if(v.ended){rec.stop();return}ctx.drawImage(v,0,0,c.width,c.height);requestAnimationFrame(draw)};v.play();draw()})}
function closeModal(){$('#modal').classList.remove('show');$('#modal').innerHTML=''}
if(token)start();