let token=localStorage.getItem('vigyapan_admin_token')||'';let DB={};const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/\\/g,'\\\\').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const api=()=>window.VIGYAPAN_CONFIG.API;
function showToast(t,ok=true){const e=$('#toast');e.textContent=t;e.className=ok?'ok':'bad';e.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.style.display='none',2800)}
function jsonp(url,timeout=20000){return new Promise((resolve,reject)=>{const cb='a_'+Date.now()+Math.random().toString(16).slice(2);const s=document.createElement('script');let done=false;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(to);s.remove();delete window[cb];fn(v)};const to=setTimeout(()=>finish(reject,Error('Request timeout')),timeout);window[cb]=d=>finish(resolve,d);s.onerror=()=>finish(reject,Error('API error'));s.src=url+(url.includes('?')?'&':'?')+'callback='+cb;document.body.appendChild(s)})}
async function get(action,extra={}){return jsonp(api()+'?'+new URLSearchParams({action,...extra}).toString())}
async function post(body){return get(body.action,{token,...Object.fromEntries(Object.entries(body).filter(([k])=>k!=='action'))})}
async function login(){try{const d=await get('login',{password:$('#password').value});if(!d.ok)return showToast(d.error||'Invalid password',false);token=d.token;localStorage.setItem('vigyapan_admin_token',token);await start()}catch(e){showToast('CMS connection failed: '+e.message,false)}}
function logout(){localStorage.removeItem('vigyapan_admin_token');token='';location.reload()}
async function start(){if(!token)return;try{const d=await get('authCheck',{token});if(!d.ok){localStorage.removeItem('vigyapan_admin_token');token='';return}$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load();bindTabs();renderDashboard()}catch(e){showToast('Session expired. Login again.',false)}}
async function load(){const d=await get('public');if(!d||d.ok===false)throw Error(d?.error||'CMS response failed');DB=d}
async function refresh(msg){await load();renderDashboard();showToast(msg||'Saved ✓')}
function bindTabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.tab);if(innerWidth<800)toggleSide()})}
function toggleSide(){document.querySelector('aside').classList.toggle('open')}
function renderDashboard(){renderTab('dashboard')}
function renderTab(tab){const c=$('#content');if(tab==='dashboard')c.innerHTML=dashboard();else if(tab==='settings')c.innerHTML=settings();else if(tab==='hero')c.innerHTML=crud('hero','Hero Slider','hero');else if(tab==='services')c.innerHTML=crud('services','Services','services');else if(tab==='products')c.innerHTML=crud('products','Products','products');else if(tab==='plans')c.innerHTML=crud('plans','Plans','plans');else if(tab==='gallery')c.innerHTML=crud('gallery','Gallery / Video','gallery');else if(tab==='testimonials')c.innerHTML=crud('testimonials','Testimonials','testimonials')}
function dashboard(){return `<div class="pageHead"><div><span class="kicker">MASTER CONTROL</span><h1>Website Dashboard</h1><p>Every important part of the public website can be controlled from here.</p></div><a class="btn gold" href="index.html" target="_blank">Open Website ↗</a></div><div class="stats"><div class="stat"><b>${DB.hero?.length||0}</b><span>Hero Slides</span></div><div class="stat"><b>${DB.services?.length||0}</b><span>Services</span></div><div class="stat"><b>${DB.products?.length||0}</b><span>Products</span></div><div class="stat"><b>${DB.gallery?.length||0}</b><span>Gallery / Video</span></div><div class="stat"><b>${DB.plans?.length||0}</b><span>Plans</span></div><div class="stat"><b>${DB.testimonials?.length||0}</b><span>Testimonials</span></div></div><div class="panel dashboardTips"><h3>Master CMS</h3><div class="tipGrid"><div>🖼️ <b>Media</b><span>Upload, compress and publish images/videos to Drive.</span></div><div>🎨 <b>Brand</b><span>Logo, name, tagline, colours and contact details.</span></div><div>🧩 <b>Content</b><span>Hero, services, products, plans, gallery and testimonials.</span></div><div>📍 <b>Map</b><span>Paste Google Maps iframe or embed URL in Site Settings.</span></div></div></div>`}
const settingKeys=['siteName','siteTagline','logoText','logoSub','logoUrl','primaryColor','phone','email','address','whatsapp','facebook','instagram','youtube','linkedin','heroInterval','aboutEyebrow','aboutTitle','aboutText','galleryTitle','gallerySubtitle','productsTitle','servicesTitle','plansTitle','contactTitle','contactSubtitle','mapEmbed','footerText'];
function settings(){return `<div class="pageHead"><div><span class="kicker">GLOBAL CONTROL</span><h1>Site Settings</h1><p>Logo, brand identity, contact, map, headings and social links.</p></div></div><div class="panel"><div class="logoSetting"><div id="settingLogoPreview" class="logoPreview"></div><div><b>Website Logo</b><p>Upload a transparent PNG/JPG. It will appear beside the website name in the top header and footer.</p><input id="logoFile" type="file" accept="image/*" onchange="previewLogo(event)"><button class="btn green" onclick="uploadLogo()">Upload Logo</button></div></div><div class="formGrid">${settingKeys.map(k=>fieldSetting(k,setting(k))).join('')}</div><div class="saveBar"><button class="btn green" onclick="saveSettings()">Save All Changes</button></div></div><div class="panel"><h3>Admin Password</h3><div class="row"><input id="newPass" type="password" placeholder="Minimum 6 characters"><button class="btn" onclick="changePassword()">Change Password</button></div></div>`}
function setting(k){const x=(DB.settings||[]).find(r=>String(r.key)===String(k));return x?x.value:''}
function fieldSetting(k,v){const area=['aboutText','contactSubtitle','footerText'].includes(k);return `<div class="field ${area?'full':''}"><label>${k}</label>${area?`<textarea id="set_${k}">${esc(v)}</textarea>`:`<input id="set_${k}" value="${esc(v)}">`}</div>`}
function previewLogo(e){const f=e.target.files?.[0];if(!f)return;const u=URL.createObjectURL(f);$('#settingLogoPreview').innerHTML=`<img src="${u}">`}
async function saveSettings(){try{const items=settingKeys.map(k=>({key:k,value:$('#set_'+k).value}));const d=await post({action:'saveSettings',items});if(!d.ok)throw Error(d.error);await refresh('Settings saved ✓')}catch(e){showToast(e.message,false)}}
async function uploadLogo(){const f=$('#logoFile')?.files?.[0];if(!f)return showToast('Select a logo first',false);try{showToast('Preparing logo…');const data=await prepareImage(f,160*1024);const name='SITE_LOGO_'+Date.now()+'.jpg';const d=await post({action:'uploadMedia',fileName:name,mimeType:'image/jpeg',data});if(!d.ok)throw Error(d.error);await post({action:'saveSettings',items:[{key:'logoUrl',value:d.url}]});$('#set_logoUrl').value=d.url;await refresh('Logo uploaded and published ✓')}catch(e){showToast('Logo upload failed: '+e.message,false)}}
const schemas={hero:{sheet:'HERO',fields:[['imageUrl','Image URL / uploaded file','text'],['titleSmall','Small Heading','text'],['title1','Main Heading 1','text'],['title2','Main Heading 2','text'],['description','Description','textarea'],['button1','Button 1','text'],['button1Link','Button 1 Link','text'],['button2','Button 2','text'],['button2Link','Button 2 Link','text'],['sort','Order','number'],['active','Active','selectYESNO']]},services:{sheet:'SERVICES',fields:[['icon','Icon / Emoji','text'],['name','Service Name','text'],['description','Description','textarea'],['sort','Order','number'],['active','Active','selectYESNO']]},products:{sheet:'PRODUCTS',fields:[['name','Product Name','text'],['price','Price','text'],['imageUrl','Image URL / uploaded file','text'],['shortDescription','Short Description','text'],['description','Full Description','textarea'],['features','Features (use | between items)','textarea'],['category','Category','text'],['sort','Order','number'],['active','Active','selectYESNO']]},plans:{sheet:'PLANS',fields:[['name','Plan Name','text'],['tagline','Tagline','text'],['price','Price','text'],['period','Period','text'],['color','Color','text'],['features','Features (use | between items)','textarea'],['sort','Order','number'],['active','Active','selectYESNO'],['buttonText','Button Text','text'],['buttonLink','Button Link','text']]},gallery:{sheet:'GALLERY',fields:[['section','Section','text'],['type','Type','selectMedia'],['title','Title','text'],['mediaUrl','Media URL / uploaded file','text'],['thumbUrl','Thumbnail URL','text'],['sort','Order','number'],['active','Active','selectYESNO']]},testimonials:{sheet:'TESTIMONIALS',fields:[['quote','Quote','textarea'],['name','Client Name','text'],['role','Role / Company','text'],['sort','Order','number'],['active','Active','selectYESNO']]}};
function crud(key,title,skey){const rows=[...(DB[skey]||[])].sort((a,b)=>(+a.sort||0)-(+b.sort||0));return `<div class="pageHead"><div><span class="kicker">CONTENT CONTROL</span><h1>${title}</h1><p>Add, edit, publish/unpublish and delete items.</p></div><div><button class="btn gold" onclick="editItem('${key}','')">+ Add New</button>${['hero','gallery'].includes(key)?`<button class="btn" onclick="bulkUpload('${key}')">⇧ Bulk Upload</button>`:''}</div></div><div class="panel"><div class="list">${rows.length?rows.map(x=>itemRow(key,x)).join(''):'<div class="empty">No items yet.</div>'}</div></div>`}
function itemRow(key,x){let image=x.imageUrl||x.mediaUrl||'';return `<div class="item"><div>${image&&String(x.type)!=='video'?`<img class="thumb" src="${esc(image)}" onerror="this.style.opacity='.2'">`:String(x.type)==='video'?'<div class="thumb videoThumb">▶</div>':'<div class="thumb"></div>'}</div><div><h4>${esc(x.name||x.title||x.section||x.quote?.slice(0,45)||'Untitled')}</h4><p>${esc(x.price||x.description||x.shortDescription||x.role||x.section||'')}</p><span class="status ${String(x.active).toUpperCase()==='YES'?'on':'off'}">${String(x.active).toUpperCase()==='YES'?'LIVE':'HIDDEN'}</span></div><div class="itemActions"><button class="iconBtn" onclick='editItem("${key}","${esc(x.id)}")'>Edit</button><button class="iconBtn danger" onclick='removeItem("${key}","${esc(x.id)}")'>Delete</button></div></div>`}
function editItem(key,id){const s=schemas[key],row=(DB[key]||[]).find(x=>String(x.id)===String(id))||{id:key.toUpperCase().slice(0,2)+(Date.now()%100000),sort:(DB[key]||[]).length+1,active:'YES'};$('#modal').innerHTML=`<div class="modalBox"><div class="modalHead"><h2>${id?'Edit':'Add'} ${key}</h2><button class="close" onclick="closeModal()">×</button></div><input type="hidden" id="f_id" value="${esc(row.id)}"><div class="formGrid" id="editForm">${s.fields.map(([f,l,t])=>field(f,l,t,row[f]??'')).join('')}</div>${['hero','products','gallery'].includes(key)?uploadUI(key):''}<div class="saveBar"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn green" onclick="saveItem('${key}')">Save & Publish</button></div></div>`;$('#modal').classList.add('show')}
function field(f,l,t,v){if(t==='textarea')return `<div class="field full"><label>${l}</label><textarea id="f_${f}">${esc(v)}</textarea></div>`;if(t==='selectYESNO')return `<div class="field"><label>${l}</label><select id="f_${f}"><option ${String(v).toUpperCase()==='YES'?'selected':''}>YES</option><option ${String(v).toUpperCase()!=='YES'?'selected':''}>NO</option></select></div>`;if(t==='selectMedia')return `<div class="field"><label>${l}</label><select id="f_${f}"><option value="image" ${String(v).toLowerCase()==='image'?'selected':''}>image</option><option value="video" ${String(v).toLowerCase()==='video'?'selected':''}>video</option></select></div>`;return `<div class="field"><label>${l}</label><input id="f_${f}" type="${t==='number'?'number':'text'}" value="${esc(v)}"></div>`}
function uploadUI(key){return `<div class="uploadBox"><b>Upload ${key==='gallery'?'images / videos':'image'}</b><small>Files are compressed in your browser and uploaded directly to Drive.</small><input id="fileInput" type="file" ${key==='gallery'?'multiple':''} accept="${key==='gallery'?'image/*,video/*':'image/*'}" onchange="previewFiles(event)"><div class="previewGrid" id="previewGrid"></div><div id="uploadQueue" class="uploadQueue"></div></div>`}
function previewFiles(e){const box=$('#previewGrid');box.innerHTML='';[...e.target.files].forEach(f=>{const u=URL.createObjectURL(f);box.insertAdjacentHTML('beforeend',f.type.startsWith('video/')?`<video src="${u}" controls></video>`:`<img src="${u}">`)})}
async function saveItem(key){try{const s=schemas[key],obj={id:$('#f_id').value};s.fields.forEach(([f])=>obj[f]=$('#f_'+f)?.value||'');const files=$('#fileInput')?.files;if(files?.length){if(key==='gallery'&&files.length>1)return doBulkUpload(key,files);const f=files[0];const data=await prepareMedia(f);const d=await post({action:'uploadMedia',fileName:'UP_'+Date.now()+'_'+safeFileName(f.name),mimeType:f.type,data});if(!d.ok)throw Error(d.error);if(key==='gallery'){obj.mediaUrl=d.url;obj.thumbUrl=d.url;obj.type=f.type.startsWith('video/')?'video':'image'}else obj.imageUrl=d.url}const d=await post({action:'saveRows',sheet:s.sheet,rows:[obj]});if(!d.ok)throw Error(d.error);await refresh('Saved & published ✓');closeModal()}catch(e){showToast('Save failed: '+e.message,false)}}
async function removeItem(key,id){if(!confirm('Delete this item?'))return;try{const d=await post({action:'deleteRow',sheet:schemas[key].sheet,id});if(!d.ok)throw Error(d.error);await refresh('Deleted ✓')}catch(e){showToast(e.message,false)}}
function safeFileName(n){return String(n||'file').replace(/[^a-zA-Z0-9._-]/g,'_')}
async function doBulkUpload(key,passed){const files=passed?[...passed]:[...($('#bulkFiles')?.files||[])];if(!files.length)return showToast('Select files first',false);if(!passed){const accept=key==='hero'?'image/*':'image/*,video/*';$('#modal').innerHTML=`<div class="modalBox"><div class="modalHead"><h2>Bulk Upload ${key}</h2><button class="close" onclick="closeModal()">×</button></div><div class="uploadBox"><input id="bulkFiles" type="file" multiple accept="${accept}"><div id="uploadQueue" class="uploadQueue"></div></div><div class="saveBar"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn green" onclick="doBulkUpload('${key}')">Upload & Publish</button></div></div>`;$('#modal').classList.add('show');return}if(!$('#uploadQueue')){$('#modal').innerHTML=`<div class="modalBox"><div class="uploadQueue" id="uploadQueue"></div></div>`;$('#modal').classList.add('show')}let order=(DB[key]||[]).length+1,rows=[];for(const f of files){try{setUploadStatus(f.name,'Preparing…');const data=await prepareMedia(f);setUploadStatus(f.name,'Uploading…');const d=await post({action:'uploadMedia',fileName:'BULK_'+Date.now()+'_'+safeFileName(f.name),mimeType:f.type,data});if(!d.ok)throw Error(d.error);const base=f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ');if(key==='hero')rows.push({id:'H'+Date.now()+order,imageUrl:d.url,titleSmall:'LET’S GROW YOUR BRAND TOGETHER',title1:base,title2:'Powerful Results',description:'Creative advertising solutions for your business.',button1:'Explore Services',button1Link:'#services',button2:'Get a Free Quote',button2Link:'#contact',sort:order++,active:'YES'});else rows.push({id:'G'+Date.now()+order,section:f.type.startsWith('video/')?'Video Production':'New Gallery',type:f.type.startsWith('video/')?'video':'image',title:base,mediaUrl:d.url,thumbUrl:d.url,sort:order++,active:'YES'});setUploadStatus(f.name,'Published ✓','done')}catch(e){setUploadStatus(f.name,e.message,'error')}}if(rows.length){const d=await post({action:'saveRows',sheet:schemas[key].sheet,rows});if(!d.ok)throw Error(d.error)}await refresh(rows.length+' file(s) published ✓');setTimeout(closeModal,500)}
function bulkUpload(key){doBulkUpload(key)}
function setUploadStatus(name,msg,state='work'){const box=$('#uploadQueue');if(!box)return;const id='u_'+btoa(unescape(encodeURIComponent(name))).replace(/[^a-zA-Z0-9]/g,'');let el=document.getElementById(id);if(!el){el=document.createElement('div');el.id=id;el.className='uploadRow';box.appendChild(el)}el.className='uploadRow '+state;el.innerHTML=`<span>${esc(name)}</span><span>${esc(msg)}</span>`}
async function prepareMedia(file){if(file.type.startsWith('image/'))return prepareImage(file,180*1024);if(file.type.startsWith('video/'))return prepareVideo(file,420*1024);return fileToData(file)}
function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function prepareImage(file,target){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{let scale=Math.min(1,1600/Math.max(img.width,img.height)),q=.82,data='';for(let i=0;i<7;i++){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);data=c.toDataURL('image/jpeg',q);if(data.length<target*1.37)break;q=Math.max(.42,q-.08);scale*=.88}resolve(data)};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function prepareVideo(file,target){if(file.size<=target)return fileToData(file);if(!('MediaRecorder' in window))return fileToData(file);const v=document.createElement('video');v.src=URL.createObjectURL(file);v.muted=true;v.playsInline=true;await new Promise((res,rej)=>{v.onloadedmetadata=res;v.onerror=rej});const scale=Math.min(1,640/Math.max(v.videoWidth,v.videoHeight));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(v.videoWidth*scale));c.height=Math.max(1,Math.round(v.videoHeight*scale));const ctx=c.getContext('2d');const stream=c.captureStream(12);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp8')?'video/webm;codecs=vp8':'video/webm';const duration=Math.max(1,v.duration||1);const rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:Math.max(60000,Math.min(160000,target*8/duration))});const chunks=[];return new Promise(resolve=>{rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const b=new Blob(chunks,{type:mime});fileToData(b).then(resolve)};rec.start(300);v.play();const draw=()=>{if(v.ended||v.currentTime>=duration){rec.stop();return}ctx.drawImage(v,0,0,c.width,c.height);requestAnimationFrame(draw)};draw()})}
function closeModal(){$('#modal').classList.remove('show');$('#modal').innerHTML=''}
if(token)start();