let DATA={};let heroIndex=0;let heroTimer=null;let lastVersion='';let pollBusy=false;let galleryFilter='all';const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
function apiUrl(action='public',extra={}){const base=(window.VIGYAPAN_CONFIG?.API||'').trim();const q=new URLSearchParams({action,...extra});return base+'?'+q.toString()}
function toggleNav(){document.querySelector('#nav').classList.toggle('open')}
function jsonp(url,timeoutMs=15000){return new Promise((resolve,reject)=>{const cb='cb_'+Date.now()+'_'+Math.floor(Math.random()*9999);const s=document.createElement('script');let done=false;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);s.remove();delete window[cb];fn(v)};const timer=setTimeout(()=>finish(reject,new Error('API timeout')),timeoutMs);window[cb]=d=>finish(resolve,d);s.onerror=()=>finish(reject,new Error('API error'));s.src=url+(url.includes('?')?'&':'?')+'callback='+cb;document.body.appendChild(s)})}
function setting(k,def=''){const r=(DATA.settings||[]).find(x=>String(x.key)===String(k));return r&&r.value!==undefined&&r.value!==''?r.value:def}
function mediaUrl(u){let s=String(u||'').trim();if(!s)return '';if(s.startsWith('http://'))s=s.replace('http://','https://');return s}
function fallbackData(){return {version:'local',settings:[{key:'logoText',value:'VIGYAPAN'},{key:'logoSub',value:'ADVERTISING AGENCY'},{key:'siteTagline',value:'Where Brands Get Noticed'},{key:'aboutEyebrow',value:'YOUR CREATIVE PARTNER'},{key:'aboutTitle',value:'Ideas that make your brand visible.'},{key:'aboutText',value:'Creative design, branding, printing and digital marketing solutions for ambitious businesses.'},{key:'servicesTitle',value:'Our Services'},{key:'productsTitle',value:'Our Products'},{key:'plansTitle',value:'Our Plans'},{key:'galleryTitle',value:'Our Work'},{key:'gallerySubtitle',value:'Selected designs, campaigns and creative work.'},{key:'contactTitle',value:'Get In Touch'},{key:'contactSubtitle',value:'Let’s discuss how we can help grow your business.'}],hero:[{id:'FH1',imageUrl:'assets/hero-01.svg',titleSmall:'LET’S GROW YOUR BRAND TOGETHER',title1:'Creative Ideas',title2:'Powerful Results',description:'Design, branding, printing and digital marketing under one roof.',button1:'Explore Services',button1Link:'#services',button2:'Get a Free Quote',button2Link:'#contact',sort:1,active:'YES'}],services:[{id:'S1',icon:'✦',name:'Graphic Designing',description:'Premium designs for every business need.',sort:1,active:'YES'},{id:'S2',icon:'◈',name:'Digital Marketing',description:'Creative campaigns and content for growth.',sort:2,active:'YES'},{id:'S3',icon:'▣',name:'Printing & Branding',description:'Professional print and branding solutions.',sort:3,active:'YES'},{id:'S4',icon:'▶',name:'Video Production',description:'Reels, ads and business videos.',sort:4,active:'YES'}],products:[],plans:[],gallery:[],contact:[],testimonials:[]}}
async function loadData(silent=false){if(pollBusy)return;try{pollBusy=true;const api=window.VIGYAPAN_CONFIG?.API;if(!api||api.includes('PASTE_')){if(!lastVersion){DATA=fallbackData();lastVersion='local';renderAll()}return}const d=await jsonp(apiUrl('public'));if(!d||d.ok===false||!d.version)throw Error(d?.error||'Invalid CMS response');if(d.version===lastVersion)return;const old=lastVersion;lastVersion=String(d.version);DATA=d;renderAll();if(old&&old!=='local'&&!silent)showToast('Website updated ✓')}catch(e){if(!lastVersion){DATA=fallbackData();lastVersion='local';renderAll()} if(!silent)showToast('CMS connection unavailable — showing safe fallback')}finally{pollBusy=false;hideLoading()}}
function renderAll(){renderSettings();renderHero();renderServices();renderProducts();renderPlans();renderGallery();renderTestimonials();renderContact()}
function renderSettings(){const name=setting('logoText',setting('siteName','VIGYAPAN')),sub=setting('logoSub',setting('siteTagline','ADVERTISING AGENCY')),logo=mediaUrl(setting('logoUrl',''));$('#logoText').textContent=name;$('#logoSub').textContent=sub;$('#footerLogo').textContent=name;$('#footerSub').textContent=sub;$('#pageTitle').textContent=name+' — '+sub;$('#aboutEyebrow').textContent=setting('aboutEyebrow');$('#aboutTitle').textContent=setting('aboutTitle');$('#aboutText').textContent=setting('aboutText');$('#servicesTitle').textContent=setting('servicesTitle','Our Services');$('#productsTitle').textContent=setting('productsTitle','Our Products');$('#plansTitle').textContent=setting('plansTitle','Our Plans');$('#galleryTitle').textContent=setting('galleryTitle','Our Work');$('#gallerySubtitle').textContent=setting('gallerySubtitle');$('#contactTitle').textContent=setting('contactTitle');$('#contactSubtitle').textContent=setting('contactSubtitle');setLogo('#logoImg','#brandFallback',logo);setLogo('#footerLogoImg','#footerBrandFallback',logo);const socials=[['WA',setting('whatsapp')?waUrl(setting('whatsapp')):''],['f',setting('facebook')],['◎',setting('instagram')],['▶',setting('youtube')],['in',setting('linkedin')]];const html=socials.filter(x=>x[1]).map(x=>`<a href="${esc(x[1])}" target="_blank" rel="noopener">${x[0]}</a>`).join('');$('#social').innerHTML=html;$('#footerSocial').innerHTML=html;}
function setLogo(imgSel,fallbackSel,url){const im=$(imgSel),fb=$(fallbackSel);if(url){im.src=url;im.style.display='block';fb.style.display='none';im.onerror=()=>{im.style.display='none';fb.style.display='grid'}}else{im.removeAttribute('src');im.style.display='none';fb.style.display='grid'}}
function waUrl(n){let p=String(n||'').replace(/\D/g,'');if(p.length===10)p='91'+p;return 'https://wa.me/'+p}
function activeRows(key){return (DATA[key]||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>(+a.sort||0)-(+b.sort||0))}
function renderHero(){let rows=activeRows('hero');if(!rows.length)rows=fallbackData().hero;heroIndex=Math.max(0,Math.min(heroIndex,rows.length-1));$('#heroSlides').innerHTML=rows.map((x,i)=>`<div class="heroSlide ${i===heroIndex?'active':''}" style="background-image:url('${esc(mediaUrl(x.imageUrl))}')"><div class="heroCopy"><span class="eyebrow">${x.titleSmall||''}</span><h1>${x.title1||''}<br><span>${x.title2||''}</span></h1><p>${x.description||''}</p><div class="heroButtons"><a class="yellowBtn" href="${esc(x.button1Link||'#services')}">${x.button1||'Explore Services'} →</a><a class="outlineBtn" href="${esc(x.button2Link||'#contact')}">${x.button2||'Get a Free Quote'}</a></div></div></div>`).join('');$('#heroDots').innerHTML=rows.map((_,i)=>`<span class="dot ${i===heroIndex?'active':''}" onclick="heroGo(${i})"></span>`).join('');clearInterval(heroTimer);heroTimer=setInterval(heroNext,+setting('heroInterval','4500')||4500)}
function heroGo(i){const n=activeRows('hero').length||1;heroIndex=(i+n)%n;renderHero()}function heroNext(){const n=activeRows('hero').length;if(n)heroGo(heroIndex+1)}function heroPrev(){const n=activeRows('hero').length;if(n)heroGo(heroIndex-1)}
function renderServices(){let rows=activeRows('services');if(!rows.length)rows=fallbackData().services;$('#serviceGrid').innerHTML=rows.map(x=>`<article class="serviceCard" onclick="openService('${esc(x.id)}')"><div class="serviceIcon">${x.icon||'✦'}</div><h3>${x.name||''}</h3><p>${x.description||''}</p><span class="more">Explore →</span></article>`).join('')}
function openService(id){const x=(DATA.services||[]).find(r=>String(r.id)===String(id));if(!x)return;$('#productModalContent').innerHTML=`<div class="detailGrid serviceDetail"><div class="serviceBigIcon">${x.icon||'✦'}</div><div class="detailText"><span class="eyebrow">SERVICE</span><h2>${x.name}</h2><p>${x.description||''}</p><p>Tell us what you need and we’ll help you plan the right solution for your business.</p><a class="yellowBtn" target="_blank" href="${waUrl(setting('whatsapp'))}?text=${encodeURIComponent('Hello, I want details about '+x.name)}">Enquire on WhatsApp →</a></div></div>`;$('#productModal').classList.add('show')}
function renderProducts(){const rows=activeRows('products');$('#productGrid').innerHTML=rows.length?rows.map(x=>`<article class="productCard"><div class="mediaBox"><img class="productImage" src="${esc(mediaUrl(x.imageUrl))}" onerror="this.src='assets/product-visiting.svg'" loading="lazy"></div><div class="productBody"><span class="miniTag">${x.category||'PRODUCT'}</span><h3>${x.name}</h3><div class="price">${x.price||''}</div><p>${x.shortDescription||''}</p><div class="cardActions"><button class="viewBtn" onclick="openProduct('${esc(x.id)}')">View Details</button><button class="circleBtn" onclick="openZoom('${esc(x.imageUrl)}')">↗</button></div></div></article>`).join(''):'<div class="emptyState">Products will appear here when added from Admin.</div>'}
function openProduct(id){const x=(DATA.products||[]).find(p=>String(p.id)===String(id));if(!x)return;const features=String(x.features||'').split('|').filter(Boolean).map(f=>`<li>${f}</li>`).join('');$('#productModalContent').innerHTML=`<div class="detailGrid"><div><img class="detailImage" src="${esc(mediaUrl(x.imageUrl))}" onerror="this.src='assets/product-visiting.svg'"></div><div class="detailText"><span class="eyebrow">${x.category||'PRODUCT'}</span><h2>${x.name}</h2><div class="price">${x.price||''}</div><p>${x.description||x.shortDescription||''}</p><ul>${features}</ul><a class="yellowBtn" href="${waUrl(setting('whatsapp'))}?text=${encodeURIComponent('I want details for '+x.name)}" target="_blank">Enquire on WhatsApp →</a></div></div>`;$('#productModal').classList.add('show')}
function renderPlans(){const rows=activeRows('plans');$('#planGrid').innerHTML=rows.length?rows.map((x,i)=>`<article class="planCard ${i===1?'featured':''}" style="--plan:${x.color||'#315ee7'}"><span class="planBadge">${i===1?'POPULAR':'PLAN'}</span><h3>${x.name}</h3><div class="planTag">${x.tagline||''}</div><div class="planPrice">${x.price} <small>${x.period||''}</small></div><ul class="planFeatures">${String(x.features||'').split('|').filter(Boolean).map(f=>`<li>${f}</li>`).join('')}</ul><a class="planBtn" href="${esc(x.buttonLink||'#contact')}">${x.buttonText||'Get Started'} →</a></article>`).join(''):'<div class="emptyState darkEmpty">Plans will appear here when added from Admin.</div>'}
function renderGallery(){let rows=activeRows('gallery');if(galleryFilter!=='all')rows=rows.filter(x=>String(x.type).toLowerCase()===galleryFilter);$('#galleryGrid').innerHTML=rows.length?rows.map(x=>{const t=String(x.type).toLowerCase();return t==='video'?`<article class="galleryCard" onclick="openVideo('${esc(x.mediaUrl)}')"><video src="${esc(mediaUrl(x.mediaUrl))}" muted preload="metadata"></video><span class="play">▶</span><span class="galleryLabel">${x.title||''}</span></article>`:`<article class="galleryCard" onclick="openZoom('${esc(x.mediaUrl)}')"><img src="${esc(mediaUrl(x.mediaUrl))}" loading="lazy" onerror="this.closest('.galleryCard').classList.add('broken')"><span class="galleryLabel">${x.title||''}</span></article>`}).join(''):'<div class="emptyState">No media in this category yet.</div>'}
function filterGallery(type,btn){galleryFilter=type;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderGallery()}
function renderTestimonials(){let rows=activeRows('testimonials');if(!rows.length)rows=[{quote:'Professional communication, premium creative work and timely delivery.',name:'Business Client',role:'Client'},{quote:'The team understands our brand and keeps every campaign consistent.',name:'Growing Business',role:'Client'},{quote:'From printing to digital, everything is handled under one roof.',name:'Corporate Client',role:'Client'}];$('#testimonialGrid').innerHTML=rows.map(x=>`<article><div class="quoteMark">“</div><p>${x.quote||x.text||''}</p><b>${x.name||'Client'}</b><span>${x.role||''}</span></article>`).join('')}
function renderContact(){const phone=setting('phone'),email=setting('email'),address=setting('address'),wa=setting('whatsapp');$('#contactInfo').innerHTML=`<div class="contactInfo">☎ <a href="tel:${esc(phone)}">${phone||''}</a></div><div class="contactInfo">✉ <a href="mailto:${esc(email)}">${email||''}</a></div><div class="contactInfo">⌖ ${address||''}</div>`;$('#callBtn').href=phone?'tel:'+String(phone).replace(/[^+\d]/g,''):'#';$('#waBtn').href=wa?waUrl(wa)+'?text='+encodeURIComponent('Hello VIGYAPAN, I need an enquiry.'):'#';$('#footerWa').href=wa?waUrl(wa):'#';const embed=(DATA.contact||[]).find(x=>String(x.key)==='mapEmbed')?.value||setting('mapEmbed','');$('#mapWrap').innerHTML=embed?normalizeMap(embed):'<div class="mapFallback"><b>Find us in Lucknow</b><span>Add Google Maps Embed URL from Admin → Site Settings.</span></div>';const links=[['Facebook',setting('facebook')],['Instagram',setting('instagram')],['YouTube',setting('youtube')],['LinkedIn',setting('linkedin')]].filter(x=>x[1]);$('#followLinks').innerHTML=links.map(x=>`<a href="${esc(x[1])}" target="_blank" rel="noopener">${x[0]} ↗</a>`).join('')}
function normalizeMap(v){let s=String(v||'').trim();const m=s.match(/<iframe[^>]+src=["']([^"']+)["'][^>]*>/i);if(m)s=m[1];if(!/^https:\/\//i.test(s))return '<div class="mapFallback"><b>Invalid map embed URL</b><span>Paste the Google Maps iframe src URL in Admin.</span></div>';return `<iframe src="${esc(s)}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe>`}
function openVideo(u){$('#mediaStage').innerHTML=`<video controls autoplay playsinline src="${esc(mediaUrl(u))}"></video>`;$('#lightbox').classList.add('show')}
function openZoom(u){if(!u)return;$('#mediaStage').innerHTML=`<img src="${esc(mediaUrl(u))}" alt="">`;$('#lightbox').classList.add('show')}
function closeModal(id){$('#'+id).classList.remove('show');if(id==='lightbox')$('#mediaStage').innerHTML=''}
function showToast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}function hideLoading(){$('#loading').classList.add('hide')}
async function checkVersion(){if(pollBusy)return;try{const d=await jsonp(apiUrl('version'));if(d?.version&&String(d.version)!==String(lastVersion))await loadData(true)}catch(e){}}
window.addEventListener('click',e=>{if(e.target.classList.contains('modal'))e.target.classList.remove('show')});loadData(false);setInterval(checkVersion,window.VIGYAPAN_CONFIG?.POLL_MS||8000);
