let DATA={};let heroIndex=0,heroTimer;let lastVersion='';let pollBusy=false;let galleryItems=[],galleryIndex=0;const $=s=>document.querySelector(s);
function toggleNav(){document.querySelector('#nav').classList.toggle('open')}
function apiUrl(action='public'){return String(window.VIGYAPAN_CONFIG?.API||'').trim()+'?action='+encodeURIComponent(action)}
function jsonp(url,timeout=8000){return new Promise((resolve,reject)=>{const cb='cb_'+Date.now()+'_'+Math.floor(Math.random()*9999);const s=document.createElement('script');const timer=setTimeout(()=>{s.remove();delete window[cb];reject(Error('API timeout'))},timeout);window[cb]=d=>{clearTimeout(timer);s.remove();delete window[cb];resolve(d)};s.onerror=()=>{clearTimeout(timer);s.remove();delete window[cb];reject(Error('API error'))};s.src=url+'&callback='+cb;document.body.appendChild(s)})}
async function loadData(silent=false){if(pollBusy||!window.VIGYAPAN_CONFIG?.API||window.VIGYAPAN_CONFIG.API.includes('PASTE_'))return;pollBusy=true;try{const d=await jsonp(apiUrl('public'),9000);if(!d||!d.version)return;if(d.version===lastVersion)return;const old=lastVersion;lastVersion=String(d.version);DATA=d;renderAll();if(!silent&&old)showToast('Website updated automatically')}catch(e){if(!lastVersion)showToast('Website is connecting…')}finally{pollBusy=false}}
function setting(k,def=''){const r=(DATA.settings||[]).find(x=>x.key===k);return r&&r.value!==''?r.value:def}
function mediaUrl(u){return String(u||'')}
function renderAll(){renderSettings();renderHero();renderServices();renderProducts();renderPlans();renderGallery();renderContact()}
function renderSettings(){const logo=setting('logoUrl');const brand=document.querySelector('.brandmark');const footerBrand=document.querySelector('footer .brandmark');if(logo){if(brand)brand.innerHTML=`<img src="${esc(logo)}" alt="Logo">`;if(footerBrand)footerBrand.innerHTML=`<img src="${esc(logo)}" alt="Logo">`}else{if(brand)brand.textContent='A';if(footerBrand)footerBrand.textContent='A'}$('#aboutEyebrow').textContent=setting('aboutEyebrow','YOUR CREATIVE PARTNER');$('#aboutTitle').textContent=setting('aboutTitle','Ideas that make your brand visible.');$('#aboutText').textContent=setting('aboutText','We create impactful designs, engaging content and smart strategies to help businesses grow.');$('#logoText').textContent=setting('logoText','VIGYAPAN');$('#logoSub').textContent=setting('logoSub','ADVERTISING AGENCY');$('#footerLogo').textContent=setting('logoText','VIGYAPAN');$('#footerText').textContent=setting('footerText');$('#servicesTitle').textContent=setting('servicesTitle','Our Services');$('#productsTitle').textContent=setting('productsTitle','Our Products');$('#plansTitle').textContent=setting('plansTitle','Our Plans');$('#galleryTitle').textContent=setting('galleryTitle','Our Work');$('#gallerySubtitle').textContent=setting('gallerySubtitle','Some of our recent designs & campaigns');$('#contactTitle').textContent=setting('contactTitle','Get In Touch');$('#contactSubtitle').textContent=setting('contactSubtitle','Let’s discuss how we can help grow your business.');const socials=[['WA',setting('whatsapp')?'https://wa.me/'+setting('whatsapp'):null],['f',setting('facebook')],['◎',setting('instagram')],['▶',setting('youtube')],['in',setting('linkedin')]];const html=socials.filter(x=>x[1]).map(x=>`<a href="${esc(x[1])}" target="_blank" rel="noopener">${x[0]}</a>`).join('');$('#social').innerHTML=html;$('#footerSocial').innerHTML=html}
function renderHero(){const rows=(DATA.hero||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>(+a.sort||0)-(+b.sort||0));if(!rows.length)return;heroIndex=Math.min(heroIndex,rows.length-1);$('#heroSlides').innerHTML=rows.map((x,i)=>`<div class="heroSlide ${i===heroIndex?'active':''}" style="background-image:url('${escCss(x.imageUrl)}')"><div class="heroOverlay"><div class="heroCopy"><span class="eyebrow">${escHtml(x.titleSmall||'')}</span><h1>${escHtml(x.title1||'')}<br><span>${escHtml(x.title2||'')}</span></h1><p>${escHtml(x.description||'')}</p><div class="heroButtons"><a class="yellowBtn" href="${escAttr(x.button1Link||'#services')}">${escHtml(x.button1||'Explore Services')} →</a><a class="outlineBtn" href="${escAttr(x.button2Link||'#contact')}">${escHtml(x.button2||'Get a Free Quote')}</a></div></div></div></div>`).join('');$('#heroDots').innerHTML=rows.map((_,i)=>`<span class="dot ${i===heroIndex?'active':''}" onclick="heroGo(${i})"></span>`).join('');clearInterval(heroTimer);heroTimer=setInterval(()=>heroNext(),Math.max(2500,+setting('heroInterval','4500')||4500))}
function heroGo(i){const n=(DATA.hero||[]).filter(x=>String(x.active).toUpperCase()==='YES').length;if(!n)return;heroIndex=(i+n)%n;renderHero()}function heroNext(){heroGo(heroIndex+1)}function heroPrev(){heroGo(heroIndex-1)}
function renderServices(){const rows=(DATA.services||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>(+a.sort||0)-(+b.sort||0));$('#serviceGrid').innerHTML=rows.map(x=>`<article class="serviceCard"><div class="serviceIcon">${escHtml(x.icon||'✦')}</div><h3>${escHtml(x.name)}</h3><p>${escHtml(x.description||'')}</p></article>`).join('')}
function renderProducts(){const rows=(DATA.products||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>(+a.sort||0)-(+b.sort||0));$('#productGrid').innerHTML=rows.map(x=>`<article class="productCard"><img class="productImage" src="${escAttr(mediaUrl(x.imageUrl))}" loading="lazy" onclick="openZoom('${esc(x.imageUrl)}')"><div class="productBody"><h3>${escHtml(x.name)}</h3><div class="price">Start from ${escHtml(x.price)}</div><p>${escHtml(x.shortDescription||'')}</p><div class="cardActions"><button class="viewBtn" onclick="openProduct('${esc(x.id)}')">View Details</button><button class="circleBtn" onclick="openZoom('${esc(x.imageUrl)}')">↗</button></div></div></article>`).join('')}
function openProduct(id){const x=(DATA.products||[]).find(p=>String(p.id)===String(id));if(!x)return;const features=String(x.features||'').split('|').filter(Boolean).map(f=>`<li>${escHtml(f)}</li>`).join('');$('#productModalContent').innerHTML=`<div class="detailGrid"><div><img src="${escAttr(x.imageUrl)}" loading="lazy" onclick="openZoom('${esc(x.imageUrl)}')"></div><div class="detailText"><span class="eyebrow">${escHtml(x.category||'PRODUCT')}</span><h2>${escHtml(x.name)}</h2><div class="price">${escHtml(x.price)}</div><p>${escHtml(x.description||x.shortDescription||'')}</p><ul>${features}</ul><a class="yellowBtn" href="https://wa.me/${escAttr(setting('whatsapp'))}?text=${encodeURIComponent('I want details for '+x.name)}" target="_blank">Enquire on WhatsApp →</a></div></div>`;$('#productModal').classList.add('show')}
function renderPlans(){const rows=(DATA.plans||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>(+a.sort||0)-(+b.sort||0));$('#planGrid').innerHTML=rows.map(x=>`<article class="planCard" style="border-top:4px solid ${escAttr(x.color||'#315ee7')}"><h3>${escHtml(x.name)}</h3><div class="planTag">${escHtml(x.tagline||'')}</div><div class="planPrice">${escHtml(x.price)} <small>${escHtml(x.period||'')}</small></div><ul class="planFeatures">${String(x.features||'').split('|').filter(Boolean).map(f=>`<li>${escHtml(f)}</li>`).join('')}</ul><a class="planBtn" style="background:${escAttr(x.color||'#4932d8')}" href="${escAttr(x.buttonLink||'#contact')}">${escHtml(x.buttonText||'Get Started')} →</a></article>`).join('')}
function renderGallery(){const rows=(DATA.gallery||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>(+a.sort||0)-(+b.sort||0));const groups={};rows.forEach(x=>{const s=String(x.section||'New Gallery').trim()||'New Gallery';(groups[s]??=[]).push(x)});const entries=Object.entries(groups);$('#galleryGrid').innerHTML=entries.map(([name,items])=>{const cover=items.find(x=>x.type!=='video')?.mediaUrl||items[0]?.thumbUrl||'';const videos=items.filter(x=>x.type==='video').length;return `<article class="galleryFolder" onclick="openGalleryFolder('${esc(name)}')"><div class="folderVisual">${cover?`<img src="${escAttr(cover)}" loading="lazy">`:'<div class="folderEmpty">MEDIA</div>'}<div class="folderBadge">${items.length} ITEMS</div>${videos?`<span class="videoBadge">${videos} VIDEO${videos>1?'S':''}</span>`:''}</div><div class="folderBody"><h3>▱ ${escHtml(name)}</h3><p>View photos & videos →</p></div></article>`}).join('')}
function openGalleryFolder(name){const rows=(DATA.gallery||[]).filter(x=>String(x.active).toUpperCase()==='YES'&&String(x.section||'New Gallery').trim()===String(name)).sort((a,b)=>(+a.sort||0)-(+b.sort||0));galleryItems=rows;galleryIndex=0;renderGalleryViewer();$('#galleryModal').classList.add('show')}
function renderGalleryViewer(){const x=galleryItems[galleryIndex];if(!x)return;const isVideo=x.type==='video';$('#galleryViewerTitle').textContent=x.title||x.section||'Gallery';$('#galleryViewerCount').textContent=`${galleryIndex+1} / ${galleryItems.length}`;$('#galleryViewerMedia').innerHTML=isVideo?`<video src="${escAttr(x.mediaUrl)}" controls autoplay playsinline style="max-width:100%;max-height:72vh"></video>`:`<img src="${escAttr(x.mediaUrl)}" loading="eager" onclick="openZoom('${esc(x.mediaUrl)}')">`;$('#galleryPrev').disabled=galleryItems.length<2;$('#galleryNext').disabled=galleryItems.length<2;}
function galleryMove(n){if(!galleryItems.length)return;galleryIndex=(galleryIndex+n+galleryItems.length)%galleryItems.length;renderGalleryViewer()}
function openVideo(u){galleryItems=[{type:'video',mediaUrl:u,title:'Video'}];galleryIndex=0;renderGalleryViewer();$('#galleryModal').classList.add('show')}
function openZoom(u){const v=$('#videoTemp');if(v)v.remove();$('#zoomImg').style.display='block';$('#zoomImg').src=mediaUrl(u);$('#lightbox').classList.add('show')}
function closeModal(id){$( '#'+id).classList.remove('show');const v=$('#videoTemp');if(v)v.remove()}
function renderContact(){const phone=setting('phone'),email=setting('email'),address=setting('address');$('#contactInfo').innerHTML=`<div class="contactInfo">☎ ${escHtml(phone||'')}</div><div class="contactInfo">✉ ${escHtml(email||'')}</div><div class="contactInfo">⌖ ${escHtml(address||'')}</div>`}
function esc(s){return String(s||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/"/g,'&quot;')}function escHtml(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function escAttr(s){return escHtml(s).replace(/'/g,'&#39;')}function escCss(s){return String(s||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\n/g,'')}
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
async function checkVersion(){if(pollBusy||!window.VIGYAPAN_CONFIG?.API)return;try{const d=await jsonp(apiUrl('version'),5000);if(d&&String(d.version)!==String(lastVersion))await loadData(true)}catch(e){}}
loadData(true);setInterval(checkVersion,window.VIGYAPAN_CONFIG?.POLL_MS||5000);
