const CFG=window.VIGYAPAN_CONFIG||{};let DATA=null,SERVER_VERSION=null,heroIndex=0,heroTimer=null;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function apiUrl(action){return `${CFG.API}?action=${encodeURIComponent(action)}`}
async function getJSON(url){const r=await fetch(url,{cache:'no-store'});return r.json()}
async function loadPublic(force=false){try{if(!CFG.API||CFG.API.includes('PASTE_'))return;const v=await getJSON(apiUrl('version'));if(!force&&SERVER_VERSION===String(v.version))return;const d=await getJSON(apiUrl('public'));if(!d||!d.settings)return;SERVER_VERSION=String(d.version);DATA=d;renderAll()}catch(e){console.warn('CMS load',e)}}
function settings(){const o={};(DATA?.settings||[]).forEach(x=>o[x.key]=x.value);return o}
function renderAll(){renderSettings();renderHero();renderServices();renderProducts();renderPlans();renderGallery();renderTestimonials();renderContact();}
function renderSettings(){const s=settings();const logo=$('#logoText')?.parentElement?.parentElement;const bm=logo?.querySelector('.brandmark');if(bm)bm.outerHTML=s.logoUrl?`<img class="brandmark" src="${esc(s.logoUrl)}" style="object-fit:contain">`:`<span class="brandmark">A</span>`['logoText','logoSub','aboutEyebrow','aboutTitle','aboutText','servicesTitle','productsTitle','plansTitle','galleryTitle','gallerySubtitle','footerText'].forEach(k=>{const el=$('#'+k);if(el&&s[k]!==undefined)el.textContent=s[k]});document.documentElement.style.setProperty('--yellow',s.primaryColor||'#f7c51e');document.title=(s.siteName||'VIGYAPAN')+' — '+(s.siteTagline||'Advertising Agency');
 const social=[['WhatsApp',s.whatsapp?'https://wa.me/'+String(s.whatsapp).replace(/\D/g,''):'' , 'W'],['Facebook',s.facebook,'f'],['Instagram',s.instagram,'◎'],['YouTube',s.youtube,'▶'],['LinkedIn',s.linkedin,'in']];
 ['social','footerSocial'].forEach(id=>{const el=$('#'+id);if(el)el.innerHTML=social.filter(x=>x[1]).map(x=>`<a href="${esc(x[1])}" target="_blank" rel="noopener" title="${x[0]}">${x[2]}</a>`).join('')});
}
function renderHero(){const rows=(DATA.hero||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>Number(a.sort)-Number(b.sort));const wrap=$('#heroSlides'),dots=$('#heroDots');if(!wrap)return;wrap.innerHTML=rows.map((x,i)=>`<article class="heroSlide ${i===heroIndex?'active':''}" style="background-image:url('${esc(x.imageUrl)}')"><div class="heroOverlay"></div><div class="container heroContent"><div class="heroText"><div class="small">${esc(x.titleSmall)}</div><h1>${esc(x.title1)}<span>${esc(x.title2)}</span></h1><p>${esc(x.description)}</p><div class="heroBtns"><a class="btn yellow" href="${esc(x.button1Link||'#services')}">${esc(x.button1)} →</a><a class="btn outline" href="${esc(x.button2Link||'#contact')}">${esc(x.button2)}</a></div></div></div></article>`).join('');dots.innerHTML=rows.map((_,i)=>`<button class="${i===heroIndex?'active':''}" onclick="heroGo(${i})"></button>`).join('');if(rows.length){heroIndex=Math.min(heroIndex,rows.length-1);clearInterval(heroTimer);heroTimer=setInterval(()=>heroNext(),Number(settings().heroInterval)||4500)}}
function heroGo(i){heroIndex=i;renderHero()}function heroNext(){const n=(DATA?.hero||[]).filter(x=>String(x.active).toUpperCase()==='YES').length;if(n){heroIndex=(heroIndex+1)%n;renderHero()}}function heroPrev(){const n=(DATA?.hero||[]).filter(x=>String(x.active).toUpperCase()==='YES').length;if(n){heroIndex=(heroIndex-1+n)%n;renderHero()}}
function renderServices(){const rows=(DATA.services||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>Number(a.sort)-Number(b.sort));$('#serviceGrid').innerHTML=rows.map(x=>`<article class="serviceCard"><div class="serviceIcon">${esc(x.icon)}</div><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p></article>`).join('')}
function renderProducts(){const rows=(DATA.products||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>Number(a.sort)-Number(b.sort));$('#productGrid').innerHTML=rows.map(x=>{const imgs=String(x.imageUrl||'').split('|').filter(Boolean);return `<article class="productCard"><div class="productImg" onclick="openImage('${esc(imgs[0]||'')}')"><img src="${esc(imgs[0]||'')}" loading="lazy" onerror="this.style.display='none'"></div><div class="productBody"><h3>${esc(x.name)}</h3><div class="price">Start from ${esc(x.price)}</div><p>${esc(x.shortDescription)}</p><div class="cardActions"><button class="smallBtn" onclick="openProduct('${esc(x.id)}')">View Details</button>${imgs.length>1?`<button class="smallBtn" onclick="openProduct('${esc(x.id)}')">${imgs.length} Images</button>`:''}</div></div></article>`}).join('')}
function openProduct(id){const x=(DATA.products||[]).find(p=>String(p.id)===String(id));if(!x)return;const imgs=String(x.imageUrl||'').split('|').filter(Boolean);$('#productModalContent').innerHTML=`<div class="productDetail"><div><img src="${esc(imgs[0]||'')}" onclick="openImage('${esc(imgs[0]||'')}')"><div style="display:flex;gap:7px;margin-top:8px;overflow:auto">${imgs.map(u=>`<img src="${esc(u)}" style="width:58px;height:58px;object-fit:cover;cursor:pointer;border-radius:5px" onclick="this.closest('.productDetail').querySelector('>div>img').src='${esc(u)}'">`).join('')}</div></div><div><div class="eyebrow">${esc(x.category)}</div><h2>${esc(x.name)}</h2><div class="price" style="font-size:19px;margin:9px 0">Start from ${esc(x.price)}</div><p style="color:#617486;font-size:13px;line-height:1.6">${esc(x.description||x.shortDescription)}</p><ul class="detailFeatures">${String(x.features||'').split('|').filter(Boolean).map(f=>`<li>${esc(f)}</li>`).join('')}</ul></div></div>`;$('#productModal').classList.add('open')}
function renderPlans(){const rows=(DATA.plans||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>Number(a.sort)-Number(b.sort));$('#planGrid').innerHTML=rows.map(x=>`<article class="planCard" style="border-top:4px solid ${esc(x.color||'#315ee7')}"><h3>${esc(x.name)}</h3><div class="planTag">${esc(x.tagline)}</div><div class="planPrice">${esc(x.price)} <small>${esc(x.period)}</small></div><ul class="features">${String(x.features||'').split('|').filter(Boolean).map(f=>`<li>${esc(f)}</li>`).join('')}</ul><a class="planCta" href="${esc(x.buttonLink||'#contact')}">${esc(x.buttonText||'Get Started')} →</a></article>`).join('')}
function renderGallery(){const rows=(DATA.gallery||[]).filter(x=>String(x.active).toUpperCase()==='YES').sort((a,b)=>Number(a.sort)-Number(b.sort));$('#galleryGrid').innerHTML=rows.map(x=>{if(String(x.type).toLowerCase()==='video')return `<article class="galleryCard" onclick="openVideo('${esc(x.mediaUrl)}')"><video src="${esc(x.mediaUrl)}" muted preload="metadata"></video><span class="play">▶</span><div class="galleryShade">${esc(x.title)}</div></article>`;return `<article class="galleryCard" onclick="openImage('${esc(x.mediaUrl)}')"><img src="${esc(x.thumbUrl||x.mediaUrl)}" loading="lazy"><div class="galleryShade">${esc(x.title)}</div></article>`}).join('')}
function renderTestimonials(){const s=settings();const data=[['testimonial1','testimonial1By'],['testimonial2','testimonial2By'],['testimonial3','testimonial3By']];const el=document.querySelector('.testGrid');if(el)el.innerHTML=data.map(x=>`<article>“${esc(s[x[0]]||'')}”<b>— ${esc(s[x[1]]||'')}</b></article>`).join('')}
function renderContact(){const c={};(DATA.contact||[]).forEach(x=>c[x.key]=x.value);const s=settings();$('#contactTitle').textContent=c.contactTitle||'Get In Touch';$('#contactSubtitle').textContent=c.contactSubtitle||'';$('#contactInfo').innerHTML=`<div>☎ ${esc(s.phone||'')}</div><div>✉ ${esc(s.email||'')}</div><div>⌖ ${esc(s.address||'')}</div>`}
function openImage(url){if(!url)return;$('#zoomImg').src=url;$('#lightbox').classList.add('open')}function openVideo(url){$('#productModalContent').innerHTML=`<video src="${esc(url)}" controls autoplay style="width:100%;max-height:75vh;border-radius:10px"></video>`;$('#productModal').classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}function toggleNav(){$('#nav').classList.toggle('open')}function showToast(t){let e=$('#toast');e.textContent=t;e.className='toast show';setTimeout(()=>e.className='toast',2400)}
window.addEventListener('DOMContentLoaded',()=>{loadPublic(true);setInterval(()=>loadPublic(false),Number(CFG.POLL_MS)||5000)});
